# Float some applications's window
windowrule = float,QQ
windowrule = float,anki
windowrule = float,qv2ray
windowrule = float,qt6ct
windowrule = float,qt5ct
windowrule = float,bleachbit
windowrule = float,calibre
windowrule = float,audacious
windowrule = float,GoldenDict
windowrule = float,netease-cloud-music
windowrule = float,fcitx5-config-qt
windowrule = float,^(com.obsproject.Studio)$
windowrule = float,thunar
windowrule = float,xdg-desktop-portal
windowrule = float,xdg-desktop-portal-gtk
windowrule = float,^(org.telegram.desktop)$
# windowrule = float,gnome-tweaks
# windowrule = float,^(org.gnome.Nautilus)$
# windowrule = float,About

# Set windows size for some floating windows
windowrule = size 62% 62%, title:^($USER - Thunar)$
windowrule = size 62% 62%, title:^($USER - Anki)$
windowrule = size 62% 62%, fcitx5-config-qt
windowrule = size 62% 62%, QQ
# windowrule = size 62% 62%, title:^(网易云音乐 — Cloud Music)$
# windowrule = size 62% 62%, netease-cloud-music
# windowrule = size 62% 62%, ^(com.obsproject.Studio)$
windowrule = size 62% 62%, ^(org.telegram.desktop)$
# windowrule = size 62% 62%, audacious
# windowrule = size 62% 62%, netease-cloud-music
# windowrule = size 62% 62%, qt6ct
# windowrule = size 62% 62%, qt5ct

# Center some windows
windowrule = center,title:^($USER - Anki)$
windowrule = center,qt6ct
windowrule = center,qt5ct
windowrule = center,QQ
windowrule = center,title:^($USER - Thunar)$
windowrule = center,^(org.telegram.desktop)$
windowrule = center,xdg-desktop-portal
windowrule = center,xdg-desktop-portal-gtk
# windowrule = center,^(org.gnome.Nautilus)$
# windowrule = center,title:^(网易云音乐 — Cloud Music)$
# windowrule = center,qv2ray
# windowrule = bordercolor rgb(FFFF00),title:^(.*Home.*)$
# windowrule = noborder,fullscreen:1
# windowrule = noshadow,fullscreen:1
# windowrule = noblur,fullscreen:1

#Special workspace
# windowrule = workspace 3,netease-cloud-music
windowrule = workspace 2,Logseq
windowrule = workspace 4,^(org.shotcut.Shotcut)$
# windowrule = workspace 3,audacious

# Make some windows transparent
# windowrulev2 = opacity 0.8 0.8,class:^(kitty)$

# windowrule = float,class:^(kitty)$,title:^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# An example for regex
# windowrulev2 = bordercolor rgb(FFFF00),title:^(.*hypr.*)$ # set bordercolor to yellow when title contains Hyprland
