# My workspace settings:
# work
# reading
# writing
# media (music & video)
# video editing (shotcut, kdenlive)
#
#Special workspace
# windowrule = workspace 3,title:^(.*☕️.*)$
# windowrule = workspace name:note-taking,Logseq
windowrule = workspace 4,^(audacious)$
windowrulev2 = workspace 4, class:netease-cloud-music
windowrulev2 = pin, class:netease-cloud-music,title:^(Cloud Music)$
windowrulev2 = workspace 4,class:netease-cloud-music, title:^(.*)(Cloud Music)$
windowrule = workspace 5,^(org.shotcut.Shotcut)$
windowrule = workspace 5,^(org.kde.kdenlive)$

# Float some applications's window
windowrule = float,anki
windowrule = float,eog
windowrule = float,qv2ray
windowrule = float,qt6ct
windowrule = float,Nutstore
windowrule = float,qt5ct
windowrule = float,bleachbit
windowrule = float,calibre-gui
windowrule = float,audacious
windowrule = float,pavucontrol
windowrule = float,GoldenDict
windowrule = float,fcitx5-config-qt
windowrule = float,^(com.obsproject.Studio)$
windowrule = float,Xdg-desktop-portal
windowrule = float,xdg-desktop-portal-gtk
windowrule = float,Xdg-desktop-portal-gtk
windowrule = float,^(org.telegram.desktop)$
windowrule = float,^(org.gnome.Calculator)$
windowrule = float,^(org.gnome.Characters)$
windowrule = float,^(org.gnome.clocks)$
windowrule = float,^(org.gnome.Nautilus)$
windowrule = float,netease-cloud-music
windowrulev2 = float,class:QQ,title:QQ
windowrulev2 = float,class:nwg-look,title:nwg-look
# windowrule = float,thunar
windowrulev2 = float,firefox,title:^(Firefox)$
# windowrule = float,class: ^$(.*fcitx5.*)$

# Set windows size for some floating windows
windowrule = size 62% 62%, kitty
windowrule = size 62% 62%, title:^(Save As)$
windowrule = size 62% 62%, Nutstore
windowrule = size 62% 62%, fcitx5-config-qt
windowrule = size 62% 62%, title:^($USER - Anki)$
windowrule = size 62% 62%, ^(org.telegram.desktop)$
windowrulev2 = size 62% 62%, class:nwg-look
windowrulev2 = size 62% 62%, class:QQ,title:QQ
windowrulev2 = size 80% 80%, class:netease-cloud-music,title:^(.*-.*)(Cloud Music)$
windowrulev2 = size 62% 62%, class:calibre-gui, title:^(calibre — || Calibre Library ||)$
windowrulev2 = size 62% 62%, class:^(org.gnome.Nautilus)$,title:[^About]
windowrulev2 = size 62% 62%, qv2ray, title:^(Qv2ray)$
# windowrule = size 62% 62%, audacious
# windowrule = size 62% 62%, title:^($USER - Thunar)$
# windowrule = size 62% 62%, title:^(网易云音乐 — Cloud Music)$
# windowrule = size 62% 62%, ^(com.obsproject.Studio)$
# windowrule = size 62% 62%, qt6ct
# windowrule = size 62% 62%, qt5ct

# Center some windows
windowrule = center,title:^($USER - Anki)$
windowrule = center,qt6ct
windowrule = center,title:^(Save As)$
windowrule = center,Nutstore
windowrule = center,calibre-gui
windowrule = center,qt5ct
windowrule = center,kitty
windowrule = center,nwg-look
windowrule = center,QQ
windowrule = center,^(org.telegram.desktop)$
windowrule = center, class:audacious
# windowrulev2 = pin, title:^(Cloud Music)$
windowrulev2 = noblur,class:netease-cloud-music, title:^(Cloud Music)$
windowrulev2 = noshadow,class:netease-cloud-music, title:^(Cloud Music)$
windowrule = center,xdg-desktop-portal
windowrule = center,xdg-desktop-portal-gtk
windowrule = center,^(org.gnome.Nautilus)$
# windowrule = center,title:^($USER - Thunar)$
# windowrule = center,qv2ray
# windowrule = bordercolor rgb(FFFF00),title:^(.*Home.*)$
# windowrule = noborder,fullscreen:1
# windowrule = noshadow,fullscreen:1
# windowrule = noblur,fullscreen:1


# Make some windows transparent
# windowrulev2 = opacity 0.8 0.8,class:^(kitty)$

# windowrule = float,class:^(kitty)$,title:^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# An example for regex
# windowrulev2 = bordercolor rgb(FFFF00),title:^(.*hypr.*)$ # set bordercolor to yellow when title contains Hyprland
#

# windowrule=nofocus,^(ibus-ui-gtk3)$
#
# Layer Rules
# layerrule = tile,fcitx
