# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# Binds basic format:
# bind=MODS,key,dispatcher,params
# 
# MOD LIST:
# SHIFT CAPS CTRL/CONTROL ALT MOD2 MOD3 SUPER/WIN/LOGO/MOD4 MOD5
$mainMod = SUPER
$mainMod1 = SUPER_SHIFT

# Launch some tools
bind = $mainMod, M, exit,
bind = $mainMod, C, killactive,
bind = $mainMod, V, togglefloating, 
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, T, togglesplit, # dwindle
bind = $mainMod, F, fullscreen, # dwindle
bind = $mainMod, S, movetoworkspacesilent,special:scratchpad,
bind = $mainMod, PERIOD, togglespecialworkspace
# bind = $mainMod, PERIOD, togglespecialworkspace,scratchpad,

bind = $mainMod, E, exec, thunar
bind = $mainMod, Return, exec, kitty
bind = $mainMod, SEMICOLON, exec, wofi --show drun
bind = $mainMod1, Return, exec, [float] kitty
bind = $mainMod1, V, exec, cliphist list | wofi -dmenu | cliphist decode | wl-copy
# bind = $mainMod, O, fakefullscreen, # dwindle
# bind = $mainMod, E, exec, nautilus

# Move focus with mainMod + arrow keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = ALT, Tab, cyclenext,

bind = $mainMod1, H, movewindow, l
bind = $mainMod1, L, movewindow, r
bind = $mainMod1, K, movewindow, u
bind = $mainMod1, J, movewindow, d

# resize active window
binde = $mainMod, right, resizeactive,100 0
binde = $mainMod, left, resizeactive,-100 0
binde = $mainMod, down, resizeactive,0 100
binde = $mainMod, up, resizeactive,0 -100

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 0, workspace, 1
bind = $mainMod, 9, workspace, 5
bind = CTRL_ALT, RIGHT, workspace, +1
bind = CTRL_ALT, LEFT, workspace, -1

# Move active window to a workspace with mainMod + SHIFT + [0-9]/arrow keys
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, RIGHT, movetoworkspace, +1
bind = $mainMod SHIFT, LEFT, movetoworkspace, -1


# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

