# float some applications's window
windowrule = float,QQ
windowrule = float,anki
windowrule = float,qv2ray
windowrule = float,calibre
windowrule = float,audacious
windowrule = float,GoldenDict
windowrule = float,gnome-tweaks
windowrule = float,netease-cloud-music
windowrule = float,fcitx5-config-qt
windowrule = float,^(org.gnome.Nautilus)$
windowrule = float,^(org.telegram.desktop)$

# Center some windows
windowrule = center,qv2ray
windowrule = center,anki
windowrule = center,^(org.gnome.Nautilus)$
windowrulev2 = noborder, fullscreen:1
# windowrule = bordercolor rgb(FFFF00),title:^(.*Home.*)$

# Make some windows transparent
# windowrulev2 = opacity 0.8 0.8,class:^(kitty)$

# windowrule = float,class:^(kitty)$,title:^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# An example for regex
# windowrulev2 = bordercolor rgb(FFFF00),title:^(.*hypr.*)$ # set bordercolor to yellow when title contains Hyprland
