# ———————————————————————————————————————————————————————————————————
# preflight before remapping
# ———————————————————————————————————————————————————————————————————
clear_all_shortcuts yes
kitty_mod alt
enabled_layouts splits:split_axis=auto

