# ———————————————————————————————————————————————————————————————————
# preflight before remapping
# ———————————————————————————————————————————————————————————————————
clear_all_shortcuts yes
kitty_mod alt
enabled_layouts splits:split_axis=auto

# ———————————————————————————————————————————————————————————————————
# kitty actions alias list
# ———————————————————————————————————————————————————————————————————
action_alias launch_tab launch --type=tab --cwd=current
action_alias launch_window launch --location=split --cwd=current
action_alias launch_vsplit launch --location=vsplit --cwd=current

