# ———————————————————————————————————————————————————————————————————
# General settings
# ———————————————————————————————————————————————————————————————————
# https://sw.kovidgoyal.net/kitty/conf/#tab-bar
tab_bar_min_tabs 1
tab_title_max_length 20

# kitty tab bar style: fade slant separator powerline custom hidden
tab_bar_style powerline
tab_powerline_style round
tab_activity_symbol 🕭

# title template
tab_title_template "{index}:{title}"

active_tab_title_template "{index}:{title}"

active_tab_font_style   bold
inactive_tab_font_style italic

# ———————————————————————————————————————————————————————————————————
